### ISSUE TITLE
Unauthorized issue when QRCodeCreate call in local system

### ISSUE THREAD

**Issue by kavi2017** [paypay/paypayopa-sdk-node#130]
**Describe the bug**
I have installed paypay code from this link https://github.com/paypay/paypayopa-sdk-node. Then i use npm run build command to get dist folder and api key/secret key/merchant id fill in config file. Then I write code for Paypay.QRCodeCreate and its throw unauthrozied issue.

**To Reproduce**
1. Go to 'After download the code, run following commands - npm run build and fill api keys to auth.js inside dist folder' - 
2. Click on 'run - add the code like 
'use strict';
 const PAYPAY = require('@paypayopa/paypayopa-sdk-node');
 PAYPAY.Configure({
  clientId: API_KEY,
  clientSecret: API_SECRET,
  productionMode: false, 
});
let payload = {
    merchantPaymentId: "my_payment_id",
    amount: {
      amount: 1,
      currency: "JPY"
    },
    codeType: "ORDER_QR",
    orderDescription: "Mune's Favourite Cake",
    isAuthorization: false,
    redirectUrl: "https://paypay.ne.jp/",
    redirectType: "WEB_LINK",
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75 Mobile/14E5239e Safari/602.1"
  };

PAYPAY.QRCodeCreate(payload, (response) => {
    console.log(response.BODY.resultInfo.code);
  });

'
4. See error -     {
	STATUS: 401,
	BODY: '{"resultInfo":{"code":"UNAUTHORIZED","message":"Unauthorized request | [OPAD1D5B358A1594F32A201766E31FCC510]","codeId":"08100016"},"data":null}'
	}

**Expected behavior**
{
  "resultInfo": {
    "code": "SUCCESS",
    "message": "Success",
    "codeId": "08100001"
  },
  "data": {
    "paymentId": "03492919691588616192",
    "status": "COMPLETED",
    "acceptedAt": 1605774970,
    "merchantPaymentId": "DEVELOPER-PANEL-DEMO-ac370acd-e656-40c3-8897-9788101b37af",
    "userAuthorizationId": "60fd75dd-8d9c-478f-be2a-d23030a7d35f",
    "amount": {
      "amount": 1000,
      "currency": "JPY"
    },
    "requestedAt": 1605774936,
    "assumeMerchant": "292138818089623552"
  }
}

**Screenshots**
![Screenshot (53)](https://user-images.githubusercontent.com/34532966/99641812-c4b78f80-2a70-11eb-9074-aeb73fde4416.png)

**Environment (please complete the following information):**
If applicable

**Additional context**

**Comment by shreyanshp** [comment]
@kavi2017 Could you please try installing from NPM `npm i @paypayopa/paypayopa-sdk-node` ?

**Comment by kavi2017** [comment]
> @kavi2017 Could you please try installing from NPM `npm i @paypayopa/paypayopa-sdk-node` ?

I already done. May i know what are the steps after install the source?

**Comment by shreyanshp** [comment]
Yup, you can find it here for all languages!

https://developer.paypay.ne.jp/products/docs/webpayment

**Comment by kavi2017** [comment]
> Yup, you can find it here for all languages!
> 
> https://developer.paypay.ne.jp/products/docs/webpayment



> Yup, you can find it here for all languages!
> 
> https://developer.paypay.ne.jp/products/docs/webpayment

I have followed the steps as mentioned above link.
1. npm i @paypayopa/paypayopa-sdk-node - done
2. Then obtained API keys and fill it in configuration and run the QRCodeCreate function it returned 
error like -     {
	STATUS: 401,
	BODY: '{"resultInfo":{"code":"UNAUTHORIZED","message":"Unauthorized request | [OPAD1D5B358A1594F32A201766E31FCC510]","codeId":"08100016"},"data":null}'
	}
Please advice if am miss anything

**Comment by shreyanshp** [comment]
Checking again, please give us a day and we'll revert

**Comment by solancer** [comment]
@kavi2017 You have missed merchant ID in the configuration, you will find the merchant ID on the top right-hand side of the dashboard upon clicking the user account menu link

**Comment by kavi2017** [comment]
> @kavi2017 You have missed merchant ID in the configuration, you will find the merchant ID on the top right-hand side of the dashboard upon clicking the user account menu link
> 
> clientId: API_NAME,
> clientSecret: API_SECRET,
> merchantId: MERCHANT_ID,
> productionMode: false

Thanks @solancer it is working now.
