### ISSUE TITLE
PAYPAY.QRCodeCreate occure Uncaught TypeError: Cannot set property 'path' of undefined 

### ISSUE THREAD

**Issue by terrierscript** [paypay/paypayopa-sdk-node#15]
I got error when call `PAYPAY.QRCodeCreate`

```js
PAYPAY.QRCodeCreate( ...
```
```
Uncaught TypeError: Cannot set property 'path' of undefined
    at Function.PayPayRestSDK.paypaySetupOptions (paypay-rest-sdk.js:34)
```
https://github.com/paypay/paypayopa-sdk-node/blob/master/src/lib/paypay-rest-sdk.ts#L76

I think this error maybe occur because `this.options` is undefined.

**Comment by shashi-pp** [comment]
Hello @terrierscript, thank you for reporting this issue. We have provided a fix this which has been merged.
