### ISSUE TITLE
Error code: 00400071

### ISSUE THREAD

**Issue by bayarmunkhD** [paypay/paypayopa-sdk-node#153]
### Describe the bug
**When I try to pay ORDER_QR, it responds with error code: _0040071_**

Hi, I am trying Pay Pay payment service and it's SDK first time.  
I have test(sandbox) API key, API secret and merchant ID.  
 
I've installed NodeJS SDK and configured all set ups.  
I've used WEB PAYMENT method.  
And successfully created order QR code.

But when I try to pay it with mobile application(logged in development mode with test user)
or web browser, PayPay server responds with error code: **0040071**.

I've googled this error code and searched it from integration documentation response code list,
but there is no explanation.

My Paypay sdk configuration:

```
PAYPAY.Configure({
    clientId: "MY_API_KEY",
    clientSecret: "MY_API_SECRET",
    merchantId: "MY_MERCHANT_ID",
    //Set True for Production Environment. By Default this is set False for Sandbox Environment.
    productionMode: false,
 });
```

My order generation payload is like:

```
   let payload = {
       merchantPaymentId: myUniqueId,
       amount: {
         amount: 1000,
         currency: "JPY"
       },
       codeType: "ORDER_QR",
       orderDescription: "Order description",
       isAuthorization: false,
       redirectUrl: "MY_URL"
       redirectType: "WEB_LINK",
     };
```

Could you guide me how could I pay in with Sandbox environment?
Or could you explain me the reason of error code 00400071?

I've also tried following repos and created successfully the order QR code,
but when I try to pay it, it responds same error.

https://github.com/paypay/paypay-sample-ecommerce-frontend
https://github.com/paypay/paypay-sample-ecommerce-backend-node

**Screenshots**
Mobile application response:
<img width="300" alt="20201215_224914" src="https://user-images.githubusercontent.com/1192859/102233471-447b3180-3f2b-11eb-8669-1f9af22d371a.jpg">

Web payment response:
<img width="977" alt="Screen Shot 2020-12-15 at 23 04 31" src="https://user-images.githubusercontent.com/1192859/102232613-51e3ec00-3f2a-11eb-9dfd-6d86bd260ef3.png">

Web payment error response:
<img width="752" alt="Screen Shot 2020-12-15 at 23 05 28" src="https://user-images.githubusercontent.com/1192859/102232671-61633500-3f2a-11eb-856c-4f2f3b85d08d.png">

**Environment:**
 - OS: [macOS Catalina, 10.15.7]
 - NodeJS Version: [11.2.0]
 - Browser [chrome]
 - Device: [Samsung s10, android 9]

**Comment by shreyanshp** [comment]
@bayarmunkhD I see, could you try the following

1. check if the test user has enough balance which you can confirm from dashboard screen in PayPay For Developers

2. Use this url https://paypay-munecake-fe.herokuapp.com/ and use your sandbox test user for transaction?

**Comment by bayarmunkhD** [comment]
@shreyanshp 
Hey tnx, it is working with this [heroku](https://paypay-munecake-fe.herokuapp.com/ ) deployed app.

Also, I think I found my problem.
The problem was with my account or merchant ID. I've created this account outside Japan.

I've created new account, got new merchant ID, now it works with no problem.

Thanks.
