### ISSUE TITLE
Question:  Is it possible to contribute to this project?

### ISSUE THREAD

**Issue by KeisukeYamashita** [paypay/paypayopa-sdk-node#16]
## Why

Because only developers PR's from PayPay are reviewed, approved.

If so or if there are any contribution rules, it is better to add a contribution guideline for non-PayPay developers.
This is a public repository so if it is possible, I want to contribute.

Thanks in advance.

**Comment by shreyanshp** [comment]
Thank you so much @KeisukeYamashita for your interest in our SDK project, I really appreciate your time and efforts on this.
I have been tracking your issues and open pull requests and those are amazing!

However as of now, we are still setting up unit tests, CI/CD pipeline, contributor's legal agreement from our side, the basic stuff to provide a better environment for you and rest of developers, and we have a target to finishing those in next couple of weeks, I would definitely respond back on this thread when we are done with that, in the meantime I would also go through your open PR's and close this issue for now

Feel free to reach out to us if any issue or queries!

**Comment by KeisukeYamashita** [comment]
Thank you for the reply! The SDK is great and I'd like to contribute again!
