### ISSUE TITLE
Connect with PayPal And or Email Pay me Gifts Catch Cashier to Pay me Gifts Catch Cashier to PayPal Account Connection

### ISSUE THREAD

**Issue by DANIEL-FONT-CEO** [paypay/paypayopa-sdk-node#174]
![Screenshot_2021-01-26_120823.jpg](https://user-images.githubusercontent.com/32707498/105901582-6d82ed80-5fd2-11eb-92e9-a6d10ca008dc.jpg)

**Comment by DANIEL-FONT-CEO** [comment]
- `![Screenshot_2021-01-26_120844.jpg](https://user-images.githubusercontent.com/32707498/105901523-5a701d80-5fd2-11eb-8275-7a8ddae12dab.jpg)`

**Comment by DANIEL-FONT-CEO** [comment]
![Screenshot_2021-01-26_111755.jpg](https://user-images.githubusercontent.com/32707498/105901682-92776080-5fd2-11eb-83cc-39ac4f438463.jpg)

**Comment by DANIEL-FONT-CEO** [comment]
The payments are working as far as I can see. But I'm not really receiveing any particular pay out showing up in my Account PAYPal Payment Log

**Comment by shreyanshp** [comment]
@DANIEL-FONT-CEO Please check if the payment provider, PayPay is what you are looking for
