### ISSUE TITLE
PayPayRestSDK class should be public

### ISSUE THREAD

**Issue by tilfin** [paypay/paypayopa-sdk-node#188]
When using this SDK in a multi-tenant service, you need create the PayPayRestSDK class instance with the tenant's client configuration for a request.
https://github.com/paypay/paypayopa-sdk-node/blob/master/src/lib/paypay-rest-sdk.ts#L15

**Comment by shreyanshp** [comment]
@solancer Please check this

**Comment by solancer** [comment]
@tilfin could you elaborate some more on the tenant service, what do you mean by "tenant's client configuration"?

**Comment by tilfin** [comment]
We're developing SaaS for mobile order and pay. The same API server has to accept requests from all of the tenant clients. So the server must process with a different PayPay client ID and secret per a request.

It's similar how to AWS's cloud API server changing the target account to process each request with AWS ACCOUNT ID and SECRET.
Our **tenant** has the same meaning as **account** in AWS.

**Comment by solancer** [comment]
@tilfin Could you help us with a code sample on how you plan on extending the capabilities to achieve this? say like if were to make these changes what properties would you need to modify?

**Comment by tilfin** [comment]
@solancer I would like to create a PayPayRestSDK instance by specified tenant's paypay settings for each request to our API server. 

```js
const { PayPayRestSDK } = require('@paypayopa/paypayopa-sdk-node/dist/lib/paypay-rest-sdk');
const app = require('express')();

app.post('/:tenantId/payaments/qrcode', (req, res) => {
   const tenantConf = getTenantConfiguration(req.params.tenantId);
   const paypayRestSdk = new PayPayRestSDK(tenantConf);

    const payload = {
      merchantPaymentId: "my_payment_id",
      amount: {
          amount: 1,
          currency: "JPY"
      },
      codeType: "ORDER_QR",
      ...
    };
    paypayRestSdk.qrCodeCreate(payload, (response) => {
      res.send(response.BODY.resultInfo.code);
    });
});
```

**Comment by solancer** [comment]
@tilfin could you please write to us at opensource@paypay-corp.co.jp so that we can better look into the business requirements and any customization you would need for the same.

**Comment by tilfin** [comment]
In the first place, why is the Client instance provided as a singleton without generating a client by a library user?
You can write the code to create an instance of the Client is in SDKs of other languages (php, python, Java).

**Comment by solancer** [comment]
@tilfin it was designed initially to keep things simple for NodeJS users. To keep things backward compatible we can add another export option with the Class object

```
export const payPayRestSDK = new PayPayRestSDK();
export PayPayRestSDK; // This should solve the multi tenant issue
```

**Comment by tilfin** [comment]
@solancer It looks good to me! But there are a few things to consider. 
https://github.com/paypay/paypayopa-sdk-node/compare/master...tilfin:feature/export-PayPayRestSDK

**Comment by solancer** [comment]
@tilfin Let me run through this one and check if anything is breaking or other changes are required for this to be merged.

**Comment by solancer** [comment]
@tilfin please raise a PR with your changes
