### ISSUE TITLE
nyc in dependencies

### ISSUE THREAD

**Issue by tilfin** [paypay/paypayopa-sdk-node#206]
https://github.com/paypay/paypayopa-sdk-node/blob/master/package.json#L31
It would be appropriate to include **nyc** in **devDependencies**.

**Comment by shreyanshp** [comment]
@tilfin Thank you raising this up, would it possible for you to send in a PR for this 🙇

**Comment by tilfin** [comment]
@shreyanshp It is not good to raise the PR because Coveralls doesn't work for forked repository well.

**Comment by shreyanshp** [comment]
@tilfin I see, anyway you can raise a PR if you want, I will take care of coveralls!
