### ISSUE TITLE
Pay pay

### ISSUE THREAD

**Issue by silocory** [paypay/paypayopa-sdk-node#252]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
If applicable

**Additional context**

**Comment by curtisfennerpaypay** [comment]
Thanks for your interest in PayPay's SDKs.

I'm going to close this issue because it looks like it has been opened by mistake.

If you have a problem or question to raise, feel free to open a new issue.
