### ISSUE TITLE
Support agreeSimilarTransaction  for createPayment 

### ISSUE THREAD

**Issue by terrierscript** [paypay/paypayopa-sdk-node#298]
**Is your feature request related to a problem? Please describe.**
https://www.paypay.ne.jp/opa/doc/jp/v1.0/direct_debit#operation/createPayment
I want to use `agreeSimilarTransaction` on `createPayment`.

**Describe the solution you'd like**
In php sdk, this parameter is supported. 
https://github.com/paypay/paypayopa-sdk-php/blob/19897d0e8ad3fd2214987d72208cbeec4b726a42/src/Controllers/Payment.php#L46

**Describe alternatives you've considered**
If avoid breaking change, append `createPaymentWithAgreeSimilarTransaction` method.

**Additional context**

**Comment by curtisfennerpaypay** [comment]
This has been published as version `1.1.0` in NPM.
