### ISSUE TITLE
Ignore or preconfigure merchant ID for sandbox env

### ISSUE THREAD

**Issue by KeisukeYamashita** [paypay/paypayopa-sdk-node#43]
**Describe the bug**

The `configure` method requires `merchantId` (ref: https://github.com/paypay/paypayopa-sdk-node/blob/fdbb4e82ee60d1f2c7baffdb768874a9242ae3d0/src/lib/paypay-rest-sdk.ts#L31).

But there is no merchant ID issued for the sandbox environment. Which value should we use?

**To Reproduce**
1. Try to call the `configure` method in sandbox env.

**Expected behavior**

Clarify which merchant ID we should use for sandbox env.

**Comment by shreyanshp** [comment]
You may want to sign up on the Paypay For Developers that would provide you with the merchant ID - http://developer.paypay.ne.jp/

However for our unit tests, we should use mocks

**Comment by KeisukeYamashita** [comment]
@shreyanshp Thanks for your reply. One question 🙇 
Do you need to activate account to get merchant ID? I can't find any merchant ID.

![image](https://user-images.githubusercontent.com/23056537/91276766-eaf4c880-e7bc-11ea-975c-86447f03b94e.png)

**Comment by KeisukeYamashita** [comment]
I can't find any merchant ID on the developer console.

![スクリーンショット 2020-08-26 16 56 11](https://user-images.githubusercontent.com/23056537/91276933-21cade80-e7bd-11ea-91f9-e39013e19ef8.png)

**Comment by shreyanshp** [comment]
As of now, actually yes 😅 

In the next release, by 16th, we would try to enable this before

**Comment by shreyanshp** [comment]
As a workaround, you can get the merchant ID for sandbox from Paypay Lab - https://developer.paypay.ne.jp/develop/paypay-lab

**Comment by shreyanshp** [comment]
And also you can get it from the profile icon

![image](https://user-images.githubusercontent.com/21307950/91278017-99e5d400-e7be-11ea-982e-b55f16056730.png)

**Comment by shreyanshp** [comment]
Even without activation, you should be able to access the sandbox with the above

**Comment by KeisukeYamashita** [comment]
@shreyanshp  I understand. Thank you so much 🙇  🙇  🙇
